contacts/urls.py
from django.conf.urls.defaults import *

urlpatterns = patterns('contacts.views',

    url(r'^people/add/$',
        view = 'person.create',
        name = 'contacts_person_create',
    ),

    url(r'^people/export/$',
        view = 'person.export',
        name = 'contacts_person_export',
    ),

    url(r'^people/import/$',
        view = 'person.importCSV',
        name = 'contacts_person_import',
    ),

    url(r'^people/synchronize/$',
        view = 'person.synchronizeSPIPForm',
        name = 'contacts_person_synchronize',
    ),

    url(r'^people/map/$',
        view = 'person.map',
        name = 'contacts_person_map',
    ),

    url(r'^people/lookup/$',
        view = 'person.lookup',
        name = 'contacts_person_lookup',
    ),
    url(r'^people/stats/$',
        view = 'stats.inscription',
        name = 'contacts_stats_inscription',
    ),
    url(r'^people/updateStatus/$',
        view = 'person.updateStatus',
        name = 'contacts_person_updatestatus',
    ),
    url(r'^people/(?P<slug>[-\w]+)/delete/$',
        view = 'person.delete',
        name = 'contacts_person_delete'
    ),
    url(r'^people/(?P<slug>[-\w]+)/edit/$',
        view = 'person.update',
        name = 'contacts_person_update'
    ),
    url(r'^people/(?P<slug>[-\w]+)/cancel/$',
        view = 'person.cancel',
        name = 'contacts_person_cancel'
    ),
    url(r'^people/(?P<slug>[-\w]+)/justificantPagament.pdf$',
        view = 'reporting.justificantPagament',
        name = 'contacts_person_justificantpagament'
    ),
    url(r'^people/(?P<slug>[-\w]+)/justificantRegistre.pdf$',
        view = 'reporting.justificantRegistre',
        name = 'contacts_person_justificantregistre'
    ),
    url(r'^people/(?P<slug>[-\w]+)/mailjustificantpagament$',
        view = 'reporting.mailJustificantPagament',
        name = 'contacts_person_mailjustificantpagament'
    ),
    url(r'^people/(?P<slug>[-\w]+)/mailpagamentretrasat$',
        view = 'reporting.mailPagamentRetrasat',
        name = 'contacts_person_mailpagamentretrasat'
    ),
    url(r'^people/(?P<slug>[-\w]+)/mail/(?P<code>[-\w]+)$',
        view = 'reporting.mail',
        name = 'contacts_person_mail'
    ),
    url(r'^people/(?P<id>[-\d]+)/mailhistory/$',
        view = 'mailhistory.mail_history',
        name = 'contacts_person_mailhistory'
    ),

    url(r'^people/(?P<slug>[-\w]+)/$',
        view = 'person.detail',
        name = 'contacts_person_detail',
    ),

    url(r'^people/$',
        view = 'person.list',
        name = 'contacts_person_list',
    ),

    url(r'^mailtemplate/add/$',
        view = 'mailtemplate.create',
        name = 'contacts_mailtemplate_create',
    ),

    url(r'^mailtemplate/lookup/$',
        view = 'mailtemplate.lookup',
        name = 'contacts_mailtemplate_lookup',
    ),

    url(r'^mailtemplate/(?P<code>[-\w]+)/delete/$',
        view = 'mailtemplate.delete',
        name = 'contacts_mailtemplate_delete'
    ),
    url(r'^mailtemplate/(?P<code>[-\w]+)/edit/$',
        view = 'mailtemplate.update',
        name = 'contacts_mailtemplate_update'
    ),
    url(r'^mailtemplate/(?P<code>[-\w]+)/copy/$',
        view = 'mailtemplate.copy',
        name = 'contacts_mailtemplate_copy'
    ),

    url(r'^mailtemplate/(?P<code>[-\w]+)/$',
        view = 'mailtemplate.detail',
        name = 'contacts_mailtemplate_detail',
    ),

    url(r'^mailtemplate/$',
        view = 'mailtemplate.list',
        name = 'contacts_mailtemplate_list',
    ),

    url(r'^course/add/$',
        view = 'course.create',
        name = 'contacts_course_create',
    ),

    url(r'^course/lookup/$',
        view = 'course.lookup',
        name = 'contacts_course_lookup',
    ),

    url(r'^course/(?P<code>[-\w]+)/delete/$',
        view = 'course.delete',
        name = 'contacts_course_delete'
    ),
    url(r'^course/(?P<code>[-\w]+)/edit/$',
        view = 'course.update',
        name = 'contacts_course_update'
    ),
    url(r'^course/(?P<code>[-\w]+)/copy/$',
        view = 'course.copy',
        name = 'contacts_course_copy'
    ),

    url(r'^course/(?P<code>[-\w]+)/$',
        view = 'course.detail',
        name = 'contacts_course_detail',
    ),

    url(r'^course/$',
        view = 'course.list',
        name = 'contacts_course_list',
    ),


)

urls.py
from django.conf.urls.defaults import *
from django.views.generic import RedirectView

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Example:
    (r'^contactes/', include('django-registration-cfd.contacts.urls')),
    (r'^login/$', 'django.contrib.auth.views.login', {'template_name': 'contacts/login.html'}),
    (r'^logout/$', 'django.contrib.auth.views.logout', {'next_page': '/login'}),
    (r'^$', RedirectView.as_view(url='/login/')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    (r'^admin/', include(admin.site.urls)),
    # (r'^contactes/comments/',      include('django.contrib.comments.urls')),
    (r'^contactes/css/(?P<path>.*)$', 'django.views.static.serve', {'document_root':'public/contactes/css/','show_indexes': True}),
    (r'^contactes/js/(?P<path>.*)$', 'django.views.static.serve', {'document_root':'public/contactes/js/','show_indexes': True}),
    (r'^contactes/img/(?P<path>.*)$', 'django.views.static.serve', {'document_root':'public/contactes/img/','show_indexes': True}),
)

contacts/models.py
# coding: utf-8

from django.db import models
from django.db.models import permalink
from django.contrib.auth.models import User
from django.contrib.contenttypes import generic
from django.utils.translation import ugettext as _
from django.contrib.comments.models import Comment
from django.contrib.contenttypes.generic import GenericRelation
from django.conf import settings

from contacts.geolocation import LocationField

from datetime import date
import time
import ast


class Course(models.Model):
    code = models.CharField(_('code'), max_length=20, unique=True)
    title = models.CharField(_('title'), max_length=200)
    description = models.TextField(_('description'), blank=True)
    url_moodle = models.CharField(_('url_moodle'), max_length=200)

    date_added = models.DateTimeField(_('date added'), auto_now_add=True)
    user_add = models.ForeignKey(User, blank=True, null=True, related_name='course-add')
    date_modified = models.DateTimeField(_('date modified'), auto_now=True)
    user_modify = models.ForeignKey(User, blank=True, null=True, related_name='course-modified')

    class Meta:
        db_table = 'contacts_course'
        verbose_name = _('Course')
        verbose_name_plural = _('Courses')

    def __unicode__(self):
        return  u"%s - %s" % (self.code, self.title)


    @permalink
    def get_absolute_url(self):
        return ('contacts_course_detail', None, {
            'code': self.code,
        })

    @permalink
    def get_update_url(self):
        return ('contacts_course_update', None, {
            'code': self.code,
        })

    @permalink
    def get_delete_url(self):
        return ('contacts_course_delete', None, {
            'code': self.code,
        })

    @permalink
    def get_copy_url(self):
        return ('contacts_course_copy', None, {
            'code': self.code,
        })


CONTACT_TYPE_CHOICES = (
    ('R', _('Registrant')),
    ('G', _('Guest')),
    ('T', _('Teacher')),
)


LABORAL_CATEGORY_CHOICES = (
    ('0', 'Sin especificar'),
    ('1', 'Funcionario/a ME o CCAA'),
    ('2', 'Interino/a ME o CCAA'),
    ('3', 'Otros funcionarios (Universidades)'),
    ('4', 'Profesor/a Privada concertada'),
    ('5', 'Profesor/a Privada no concertada'),
    ('6', 'Sin experiencia docente (Magisterio/Formación inic...'),
)

LABORAL_LEVEL_CHOICES = (
    (1, 'Educación Infantil'),
    (2, 'Educación Primaria'),
    (3, 'Enseñanza Secundaria Obligatoria'),
    (4, 'Bachillerato'),
    (5, 'Formación Profesional'),
    (7, 'Enseñanzas Artísticas y de Idiomas'),
    (8,'Escuelas Oficiales de Idiomas'),
    (9,'Educación Especial '),
    (10,'Educación Permanente de  adultos'),
    (11,'Equipos Orientación Educación y Psicopedagógica '),
    (12,'Profesores de nacionalidad extranjera'),
    (13,'Personal de otros ámbitos: (Inspectores al Servicio de la Admón. Educativa, ...) '),
    (6,'Universidad'),
)

LABORAL_CUERPO_CHOICES = (
    ('0', 'Sin especificar'),
    ('1', 'Maestros'),
    ('2', 'Prof. Ens. Secundaria'),
    ('3', 'Prof. Técnicos de Form. Profes.'),
    ('4', 'Prof. de Esc. Of. De Idiomas'),
    ('5', 'Prof. de Música y Artes Esc.'),
    ('6', 'Catedr. de Música y Artes Esc.'),
    ('7', 'Maestros de taller Artes Plást. y Diseño'),
    ('8', 'Prof. de  Artes Plást. y Diseño'),
    ('9', 'Inspectores de Educación: ME o CCAA'),
    ('10', 'Catedráticos'),
    ('11', 'Prof. Universitarios.'),
)

MATH_SOCIETY_CHOICES = (
    ('1', 'Ninguna'),
    ('2', 'FEEMCAT - Federació d’Entitats per l’Ensenyament de les Matemátiques a Catalunya'),
    ('3', 'Organización Española para La Coeducación Matemática «Ada Byron»'),
    ('4', 'Sociedad Andaluza de Educación Matemática «Thales»'),
    ('5', 'Sociedad Aragonesa de Profesores de Matemáticas «Pedro Sánchez Ciruelo»'),
    ('6', 'Sociedad Asturiana de Educación Matemática «Agustín de Pedrayes»'),
    ('7', 'Sociedad Canaria de Profesores de Matemáticas «Isaac Newton»'),
    ('8', 'Asociación Castellana y Leonesa de Educación Matemática «Miguel de Guzmán»'),
    ('9', 'Sociedad dos Ensinantes de Ciencia de Galicia (ENCIGA)'),
    ('10', 'Sociedad Extremeña de Educación Matemática «Ventura Reyes Prósper»'),
    ('11', 'Sociedad Madrileña de Profesores de Matemáticas «Emma Castelnuovo»'),
    ('12', 'Sociedad Matemática de Profesores de Cantabria'),
    ('13', 'Matematika lraskasicen Nafar Elkartea Tornamira'),
    ('14', 'Sociedad «Puiq Adam» de Profesores de Matemáticas'),
    ('15', 'Societat d’Educaciò Matemática de la Comunitat Valenciana «Al-Khwarizmi»'),
    ('16', 'Sociedad Castellano Manchega de Profesores de Matemáticas (SCMPM)'),
    ('17', 'Sociedad de Educación Matemática de la región de Murcia (SEMRM)'),
    ('18', 'Sociedad Riojana de Profesores de matemáticas «A Prima»'),
    ('19', 'Asociacion Galega de Profesores de Educación Matemática (AGAPEMA)'),
    ('20', 'Sociedad Melillense de Educación Matemática'),
    ('21', 'SBM – XEIX Societat Balear de Matemàtiques'),
)

MATH_SOCIETY_CHOICES_MINI = {
    '1':'Ninguna',
    '2':'FEEMCAT',
    '3':'Ada Byron',
    '4':'SAEM-Thales',
    '5':'Aragonesa',
    '6':'Asturiana',
    '7':'Canaria',
    '8':'CyL',
    '9':'ENCIGA',
    '10':'Extremadura',
    '11':'Madrid',
    '12':'Cantabria',
    '13':'Navarra',
    '14':'Puig Adam',
    '15':'Valenciana',
    '16':'Manchega',
    '17':'Murcia',
    '18':'Riojana',
    '19':'AGAPEMA',
    '20':'Melillense',
    '21':'SBM-XEIX',
}

REVISION_CHOICES = (
    ('dataok', _('Data ok')),
    ('datanook', _('Incorrect data')),
    ('missdata', _('Missed data')),
    ('pendent', _('Pendent'))
)

STATUS_CHOICES = (
    ('pendent', 'Pendiente'),
    ('ok_notpaid', 'Revisado / No pagado'),
    ('notpaid_late', 'Pago Restrasdo'),
    ('nook_paid', 'No revisado / Pagado'),
    ('ok_all', 'Inscripción ok'),
    ('cancelled', 'Inscripción anulada'),
)


LANG_CHOICES = (
    ('1', 'Castellà'),
    ('2', 'Català')
)

class Person(models.Model):
    """Person model."""
    # DADES PERSONALS
    first_name = models.CharField(_('first name'), max_length=100)
    last_name = models.CharField(_('last name'), max_length=200)
    nickname = models.CharField(_('nickname'), max_length=100, blank=True)
    slug = models.SlugField(_('slug'), max_length=50, unique=True)
    about = models.TextField(_('about'), blank=True)
    photo = models.ImageField(_('photo'), upload_to='contacts/person/', blank=True)
    contact_type = models.CharField(_('contact type'), max_length=1,
        choices=CONTACT_TYPE_CHOICES, default='R', blank=True)
    id_card = models.CharField(_('ID card'), max_length=20, null=True,blank=True)

    # DIRECCIO - CASA
    home_address = models.CharField(_('address'), max_length=200, blank=True)
    home_postalcode = models.CharField(_('postal code'), max_length=10, blank=True)
    home_town = models.CharField(_('town'), max_length=200, null=True, blank=True)
    home_province = models.CharField(_('province'), max_length=200, blank=True)

    email_address = models.EmailField(_('email address'), blank=True)
    phone_number = models.CharField(_('phone number'), max_length=50, blank=True)
    mobile_number = models.CharField(_('mobile number'), max_length=50, blank=True)
    twitter = models.CharField(_('twitter'), max_length=22, null=True,blank=True)

    # DADES PROFESSIONALS
    laboral_category = models.CharField(_('laboral category'), max_length=1,
        choices=LABORAL_CATEGORY_CHOICES, default='0', blank=True)
    #laboral_levels = models.CommaSeparatedIntegerField(_('laboral levels'), max_length=100,
    #    choices=LABORAL_LEVEL_CHOICES, blank=True)
    laboral_levels = models.CharField(_('laboral levels'), max_length=100,null=True,blank=True)
    laboral_nrp = models.CharField(_('NRP'), max_length=30, null=True,blank=True)
    laboral_years = models.IntegerField(_('years experience'),null=True, blank=True)
    laboral_cuerpo = models.CharField(_('cos docent'),max_length=2,
        choices=LABORAL_CUERPO_CHOICES, default='0', blank=True)
    laboral_degree = models.CharField(_('degree'), max_length=200, null=True,blank=True)


    # CENTRE DE FEINA
    laboral_centername = models.CharField(_('center name'), max_length=200, null=True,blank=True)
    laboral_centercode = models.CharField(_('center code'), max_length=20, null=True,blank=True)
    laboral_centeraddress = models.CharField(_('address'), max_length=200, blank=True)
    laboral_centerpostalcode = models.CharField(_('postal code'), max_length=10, blank=True)
    laboral_centertown = models.CharField(_('town'), max_length=200, null=True, blank=True)
    laboral_centerprovince = models.CharField(_('province'), max_length=200, blank=True)
    laboral_centerphone = models.CharField(_('phone number'), max_length=50, blank=True)

    # SOCIETAT FEDERADA
    math_society = models.CharField(_('math society'),max_length=2,
        choices=MATH_SOCIETY_CHOICES, default='1', blank=True)


    remarks =  models.TextField(_('remarks'), null=True,blank=True)
    lang = models.CharField(_('lang'), max_length=1,choices=LANG_CHOICES, default='1', blank=True)
    external_id = models.IntegerField(_('external id'),db_index=True,null=True,blank=True)


    # location = LocationField(_('location'), max_length=50, blank=True, null=True)
    location = models.CharField(_('location'), max_length=50, blank=True, null=True)

    # Revisio
    courses = models.ManyToManyField('Course')
    date_registration = models.DateTimeField(_('date registration'),null=True, blank=True)
    revision = models.CharField(_('revision'), max_length=8,choices=REVISION_CHOICES, default='pendent', blank=True)
    status = models.CharField(_('status'), max_length=15,choices=STATUS_CHOICES, default='pendent', blank=True)
    paid = models.DecimalField(_('paid'),max_digits=5, decimal_places=2,null=True,blank=True)
    date_paid = models.DateTimeField(_('date paid'),null=True, blank=True)
    date_mailnotpaid = models.DateTimeField(_('date mail not paid'),null=True, blank=True)

contacts/templates/contacts/person/base.html
{% extends "contacts/base.html" %}

contacts/templates/contacts/person/detail.html
{% extends "contacts/person/base.html" %}
{% load i18n %}

{% block title %}{{ block.super }}: {{ object }}{% endblock %}

{% block content_title %}
        <span class="fn">{{ object }}</span>
        {% if object.nickname %}
        <span class="alt">(<span class="nickname">{{ object.nickname }}</span>)</span>
        {% endif %}
        <div class="pull-right"><span class="label label-{{ object.get_label }}">{{ object.get_status_display }}</span></div>
{% endblock %}

{% block content %}
    <p>
        <h3>{% trans "Personal Data" %}</h3>
        {% if object.photo %}<div style="float:right;">{{ object.photo }}</div>{% endif %}
        <b>{% trans "Nom" %}:</b> {{ object.first_name }} {{ object.last_name }}
        {% if object.nickname %}
        ({{ object.nickname }})
        {% endif %}<br />
        {% if object.about %}{{ object.about|linebreaks }}{% endif %}
        <b>{% trans "ID Card" %}:</b> {{ object.id_card }}<br />
    </p>
    <hr/>
    <p>
        <h3>{% trans "Registre cursos" %}</h3>
        <b>{% trans "date registration" %}:</b> {{ object.date_registration|date:"d/m/Y" }}<br />
        <b>{% trans "Courses" %}:</b>
        <ul>
        {% for course in object.courses.all %}
            <li>{{ course.title }}</li>
        {% endfor %}
        </ul>
        <b>{% trans "Contact type" %}:</b> {{ object.get_contact_type_display }}<br />
        <b>{% trans "math society" %}:</b> {{ object.get_math_society_display }}<br />
        <b>{% trans "revision" %}:</b> {{ object.get_revision_display }}<br />
        <b>{% trans "paid" %}:</b> {{ object.paid }}<br />
        <b>{% trans "date paid" %}:</b> {{ object.date_paid|date:"d/m/Y" }}<br />
        <b>{% trans "date mail not paid" %}:</b> {{ object.date_mailnotpaid|date:"d/m/Y" }}<br />
        <b>{% trans "date mail registration" %}:</b> {{ object.date_mailregister|date:"d/m/Y" }}<br />
        {% if object.remarks %}<b>{% trans "remarks" %}:</b> {{ object.remarks|linebreaks }}{% endif %}

    </p>
    <hr/>
    <p>
        <h3>{% trans "Dades de contacte" %}</h3>
        <b>{% trans "address" %}:</b> {{ object.home_address }}<br />
        {{ object.home_postalcode }} {{ object.home_town }} {% if object.home_province %}({{ object.home_province }}){% endif %}   <br />
        <b>{% trans "email address" %}:</b> {{ object.email_address }}<br />
        <b>{% trans "phone number" %}:</b> {{ object.phone_number }}<br />
        <b>{% trans "mobile number" %}:</b> {{ object.mobile_number }}<br />
        {% if object.twitter %}<b>{% trans "twitter" %}:</b> <a href="https://twitter.com/{{ object.twitter }}">{{ object.twitter }}</a><br />{% endif %}
    </p>
    <hr/>
    <p>
        <h3>{% trans "Dades laborals" %}</h3>
        <b>{% trans "laboral category" %}:</b> {{ object.get_laboral_category_display }}<br />
        <b>{% trans "laboral levels" %}:</b> {{ object.get_laboral_levels }}<br />
        <b>{% trans "NRP" %}:</b> {{ object.laboral_nrp }}<br />
        <b>{% trans "years experience" %}:</b> {{ object.laboral_years }}<br />
        <b>{% trans "cos docent" %}:</b> {{ object.get_laboral_cuerpo_display }}<br />
        <b>{% trans "degree" %}:</b> {{ object.laboral_degree }}<br />

    </p>
    <hr/>
    <p>
        <h3>{% trans "Centre de feina" %}</h3>
        <b>{% trans "center name" %}:</b> {{ object.laboral_centername }} {% if object.laboral_centercode %}({{ object.laboral_centercode }}){% endif %}  <br />
        <b>{% trans "address" %}:</b> {{ object.laboral_centeraddress }}<br />
        {{ object.laboral_centerpostalcode }} {{ object.laboral_centertown }} {% if object.laboral_centerprovince %}({{ object.laboral_centerprovince }}){% endif %}   <br />
        <b>{% trans "phone number" %}:</b> {{ object.laboral_centerphone }}<br />
    </p>


    <small>
        {% trans 'Record created in' %} {{ object.date_added }}{% if object.user_add %} {% trans 'by' %} {{ object.user_add }}{% endif %}. {% trans 'Modified in' %} {{ object.date_modified }}{% if object.user_modify %} {% trans 'by' %} {{ object.user_modify }}{% endif %}.
    </small>
{% endblock %}

{% block actions %}
    <a href="{%  url contacts_person_list %}"  class="btn"><i class="icon-arrow-left"></i> {% trans "Return to list" %}</a>
    <a href="{{ object.get_update_url }}" class="btn"><i class="icon-edit"></i> {% trans "Edit" %}</a>
{% if object.paid %}
<a href="{{ object.get_justificantpagament_url }}" class="btn"><i class="icon-file"></i> {% trans "Justificant de pagament" %}</a>
{% endif %}
{% if object.status == 'ok_all' and object.contact_type != 'R' %}
<a href="{{ object.get_justificantregistre_url }}" class="btn"><i class="icon-file"></i> {% trans "Justificant de inscripcio" %}</a>
{% endif %}
{% if object.status == 'ok_all' and object.date_mailregister == None %}
    <a href="#modal_mail_pagament" role="button" data-toggle="modal" class="btn"><i class="icon-envelope"></i> {% trans 'Send mail inscription ok' %}</a>
{% endif %}
{% if object.status == 'notpaid_late' and object.date_mailnotpaid == None %}
    <a href="#modal_mail_pagamentretrasat" role="button" data-toggle="modal" class="btn"><i class="icon-envelope"></i> {% trans 'Send mail payment overdue' %}</a>
{% endif %}
{% if object.status == 'cancelled' %}
    <a href="{{ object.get_cancel_url }}" class="btn"><i class="icon-thumbs-up"></i> {% trans 'Get inscription back' %}</a>
{% else %}
    <a href="{{ object.get_cancel_url }}" class="btn"><i class="icon-thumbs-down"></i> {% trans 'Cancel inscription' %}</a>
{% endif %}
<a href="{{ object.get_delete_url }}" class="btn"><i class="icon-trash"></i> {% trans "Delete" %}</a>
</div>
<div class="btn-group" style="float:right;margin-top: -50px;" id="list-sendmail">
<a href="#" id="btn-sendmail" class="btn dropdown-toggle" data-toggle="dropdown"><i class="icon-envelope"></i> {% trans "Send mail" %} <span class="caret"></span></a>


{% if object.status == 'ok_all' and object.date_mailregister == None %}
<div id="modal_mail_pagament" class="modal hide fade" tabindex="-1" role="dialog">
    <div class="modal-header"><button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="myModalLabel">{% trans "Send mail inscription ok" %}</h3>
    </div>
    <div class="modal-body"><h5>{% trans "You are about to send the inscription ok mail" %}</h5></div>
    <div class="modal-footer">
    <button class="btn" data-dismiss="modal" aria-hidden="true">{% trans "Close" %}</button>
    <button class="btn btn-primary btn-mail" formaction="{{ object.get_mailjustificantpagament_url }}" data-loading-text="{% trans "sending" %}..." >{% trans "Send mail" %}</button>
    </div>
</div>
{% endif %}


{% if object.status == 'notpaid_late' and object.date_mailnotpaid == None %}
<div id="modal_mail_pagamentretrasat" class="modal hide fade" tabindex="-1" role="dialog">
    <div class="modal-header"><button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="myModalLabel">{% trans "Send mail payment overdue" %}</h3>
    </div>
    <div class="modal-body"><h5>{% trans "You are about to send a payment overdue mail" %}</h5></div>
    <div class="modal-footer">
    <button class="btn" data-dismiss="modal" aria-hidden="true">{% trans "Close" %}</button>
    <button class="btn btn-primary btn-mail" formaction="{{ object.get_mailpagamentretrasat_url }}" data-loading-text="{% trans "sending" %}..." >{% trans "Send mail" %}</button>
    </div>
</div>
{% endif %}

{% endblock %}

{% block page_js %}
    <script type="text/javascript">
        var URL_MAILTEMPLATE_LOOKUP = '{% url contacts_mailtemplate_lookup %}';
        var LINKMAIL = '{{ object.get_mail_url }}';
        var TRADUCTION = { sendmail : '{% trans "Send mail" %}' ,
                           close : '{% trans "Close" %}',
                           message_about_to_send : '{% trans "You are about to send the mail with subject: " %}',
                           sending : '{% trans "sending" %}',
                        };
    </script>
    <script src="/contactes/js/person_mail.js"></script>
{% endblock page_js %}

contacts/templates/contacts/person/update_form_old.html
    <fieldset id="personal">
            <legend>{% trans "Personal Data" %}</legend>
            <label for="id_first_name">{{ form.first_name.label }}</label>
            {{ form.first_name }}
            <label for="id_last_name">{{ form.last_name.label }}</label>
            {{  form.last_name }}
            <label for="id_id_card">{{ form.id_card.label }}</label>{{  form.id_card }}
            <label for="id_nickname">{{ form.nickname.label }}</label>{{  form.nickname }}
            <label for="id_about">{{ form.about.label }}</label>{{  form.about }}
            <label for="id_photo">{{ form.photo.label }}</label>{{  form.photo }}
        </fieldset>
        
        <fieldset id="inscripcio">
            <legend>{% trans "Registration info" %}
            <label for="id_contact_type">{{ form.contact_type.label }}</label> {{  form.contact_type }}
        </fieldset>

        <fieldset id="address">
            <legend>{% trans "Contact info" %}
            <label for="id_email_address">{{ form.email_address.label }}</label> {{  form.email_address }}
            <label for="id_phone_number">{{ form.phone_number.label }}</label> {{  form.phone_number }}
            <label for="id_mobile_number">{{ form.mobile_number.label }}</label> {{  form.mobile_number }}
            <label for="id_twitter">{{ form.twitter.label }}</label> {{  form.twitter }}
            
            <label for="id_home_address">{{ form.home_address.label }}</label> {{  form.home_address }}
            <label for="id_home_postalcode">{{ form.home_postalcode.label }}</label> {{  form.home_postalcode }}
            <label for="id_home_town">{{ form.home_town.label }}</label> {{  form.home_town }}
            <label for="id_home_province">{{ form.home_province.label }}</label> {{  form.home_province }}

        </fieldset>

        <fieldset id="gis">
        <legend>{% trans 'Location' %}</legend>
        <label for="id_location">{{ form.location.label }}</label>
        {{ form.location }}
        </fieldset>